apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "default_selector" . | indent 4 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "default_selector" . | indent 8 }}
    spec:
      hostname: {{ template "name" . }}
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "" .Values.image.imagePullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.logstash.input_syslog_port }}
          protocol: UDP
          name: syslog
        - containerPort: {{ .Values.logstash.input_beats_port }}
          protocol: TCP
          name: beats
        - containerPort: {{ .Values.logstash.input_json_port }}
          protocol: UDP
          name: json
        command: ["/deploy.sh"]
        env:
        {{- if .Values.env }}
{{ toYaml .Values.env | indent 10 }}
        {{- end }}
          - name: LOGSTASH_ENV
            value: {{ .Values.logstash.logstash_env | quote }}
          - name: INPUT_BEATS_PORT
            value: {{ .Values.logstash.input_beats_port | quote }}
          - name: INPUT_SYSLOG_PORT
            value: {{ .Values.logstash.input_syslog_port | quote }}
          - name: INPUT_JSON_PORT
            value: {{ .Values.logstash.input_json_port | quote }}
          - name: OUTPUT_DEST_HOST
            value: {{ .Values.logstash.output_dest_host | quote }}
          - name: OUTPUT_DEST_PORT
            value: {{ .Values.logstash.output_dest_port | quote }}
          - name: OUTPUT_SSL_ENABLE
            value: {{ .Values.logstash.output_ssl_enable | quote }}
          # Uncomment the below setting for TLS encryption. YOU MUST PUT THE REQUIRED FILES IN PLACE
          - name: OUTPUT_SSL_CONTENT
          #  # This is really ugly, but it works. The "|" method did not work, the trailing \n messed up sed.
            value: {{ .Values.logstash.output_ssl_content | quote }}
        {{- if .Values.nodeSelector }}
        nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
        {{- end }}
        resources:
          requests:
            cpu: 0m
        volumeMounts:
        - mountPath: /logstash/certs
          name: certs
          readOnly: true
      volumes:
      - name: certs
        configMap:
          name: certs
