apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "default_selector" . | indent 4 }}
spec:
  ports:
  - port: 5140
    protocol: UDP
    name: syslog
  - port: 5044
    protocol: TCP
    name: beats
  - port: 8000
    protocol: UDP
    name: json
  selector:
    {{- include "default_selector" . | indent 4 }}
