apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "default_selector" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.logstash.input_syslog_port }}
    protocol: UDP
    name: syslog
  - port: {{ .Values.logstash.input_beats_port }}
    protocol: TCP
    name: beats
  - port: {{ .Values.logstash.input_json_port }}
    protocol: UDP
    name: json
  selector:
    {{- include "default_selector" . | indent 4 }}
